[project]
name = "personal-website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cssmin>=0.2.0",
    "pelican-sitemap>=1.2.0",
    "pelican-webassets>=2.1.0",
    "pelican[markdown]>=4.11.0",
]
